/*********
  Q1- Write a multithreaded program thatgenerates the Fibonacci series.
  This program should work as follows: 
  The user will enter on the command line the number of Fibonacci numbers that the 
  program is to generate. The program will then create a separate thread that 
  will generate the Fibonacci numbers. When the thread finishes execution, the
  parent thread will output the sequence generated by the child thread. Because 
  the parent thread cannot begin outputting the Fibonacci sequence until the child
  thread finishes, this will require having the parent thread wait for the child 
  thread to finish.
**********/



#include <stdio.h> 
#include <stdlib.h> 
#include <unistd.h> 
#include <pthread.h> 

int n;  //global 

void * fibonacci(int f[]){
    int i;
    if(n==0||n==1){
        return &n;
    }
    f[0]=0;
    f[1]=1;
    for(i=2;i<n;++i){
        f[i]=f[i-1]+f[i-2];
    }
    pthread_exit(NULL);
}

int main() 
{ 
	int i;
	printf("Enter number \'n\' of Fibonacci numbers:\n");
	scanf("%d",&n);
	int f[n];

	pthread_t tid;
	pthread_create(&tid, NULL, fibonacci, &f);
	pthread_join(tid, NULL);
	
	//created thread will work on address of f[]
	
	for(i=0;i<n;++i){
	    printf("%d, ",f[i]);
	}
	printf("\nProgram Complete",i);
    
	pthread_exit(NULL); 

	return 0; 
} 
